/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: schema.proto */

#ifndef PROTOBUF_C_schema_2eproto__INCLUDED
#define PROTOBUF_C_schema_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif


typedef struct Config Config;
typedef struct Log Log;
typedef struct Data1 Data1;
typedef struct Data2 Data2;


/* --- enums --- */


/* --- messages --- */

/*
 * Configuración del dispositivo
 */
struct  Config
{
  ProtobufCMessage base;
  int32_t id_device;
  int32_t status_conf;
  int32_t protocol_conf;
  int32_t acc_sampling;
  int32_t gyro_sensibility;
  int32_t bme688_sampling;
  int32_t discontinuous_time;
  int32_t tcp_port;
  int32_t udp_port;
  char *host_ip_addr;
  char *ssid;
  /*
   * Se escribe passwd y no pass porque en python pass da problemas
   */
  char *passwd;
};
#define CONFIG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&config__descriptor) \
, 0, 0, 0, 0, 0, 0, 0, 0, 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


/*
 * Log de eventos
 */
struct  Log
{
  ProtobufCMessage base;
  int32_t id_device;
  int64_t time_client;
  int64_t time_server;
};
#define LOG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&log__descriptor) \
, 0, 0, 0 }


/*
 * Paquete de datos 1
 */
struct  Data1
{
  ProtobufCMessage base;
  int32_t id_device;
  int32_t temperature;
  int32_t press;
  int32_t hum;
  float co;
  float rms;
  float amp_x;
  float freq_x;
  float amp_y;
  float freq_y;
  float amp_z;
  float freq_z;
};
#define DATA_1__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&data_1__descriptor) \
, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }


/*
 * Paquete de datos 2
 */
struct  Data2
{
  ProtobufCMessage base;
  int32_t id_device;
  float racc_x;
  float racc_y;
  float racc_z;
  float rgyr_x;
  float rgyr_y;
  float rgyr_z;
  int64_t time_client;
};
#define DATA_2__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&data_2__descriptor) \
, 0, 0, 0, 0, 0, 0, 0, 0 }


/* Config methods */
void   config__init
                     (Config         *message);
size_t config__get_packed_size
                     (const Config   *message);
size_t config__pack
                     (const Config   *message,
                      uint8_t             *out);
size_t config__pack_to_buffer
                     (const Config   *message,
                      ProtobufCBuffer     *buffer);
Config *
       config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   config__free_unpacked
                     (Config *message,
                      ProtobufCAllocator *allocator);
/* Log methods */
void   log__init
                     (Log         *message);
size_t log__get_packed_size
                     (const Log   *message);
size_t log__pack
                     (const Log   *message,
                      uint8_t             *out);
size_t log__pack_to_buffer
                     (const Log   *message,
                      ProtobufCBuffer     *buffer);
Log *
       log__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   log__free_unpacked
                     (Log *message,
                      ProtobufCAllocator *allocator);
/* Data1 methods */
void   data_1__init
                     (Data1         *message);
size_t data_1__get_packed_size
                     (const Data1   *message);
size_t data_1__pack
                     (const Data1   *message,
                      uint8_t             *out);
size_t data_1__pack_to_buffer
                     (const Data1   *message,
                      ProtobufCBuffer     *buffer);
Data1 *
       data_1__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   data_1__free_unpacked
                     (Data1 *message,
                      ProtobufCAllocator *allocator);
/* Data2 methods */
void   data_2__init
                     (Data2         *message);
size_t data_2__get_packed_size
                     (const Data2   *message);
size_t data_2__pack
                     (const Data2   *message,
                      uint8_t             *out);
size_t data_2__pack_to_buffer
                     (const Data2   *message,
                      ProtobufCBuffer     *buffer);
Data2 *
       data_2__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   data_2__free_unpacked
                     (Data2 *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Config_Closure)
                 (const Config *message,
                  void *closure_data);
typedef void (*Log_Closure)
                 (const Log *message,
                  void *closure_data);
typedef void (*Data1_Closure)
                 (const Data1 *message,
                  void *closure_data);
typedef void (*Data2_Closure)
                 (const Data2 *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor config__descriptor;
extern const ProtobufCMessageDescriptor log__descriptor;
extern const ProtobufCMessageDescriptor data_1__descriptor;
extern const ProtobufCMessageDescriptor data_2__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_schema_2eproto__INCLUDED */
