syntax = "proto3";

// Configuración del dispositivo
message Config {
    string id_device = 1;                   // Identificador del dispositivo.
    int32 config_version = 2;               // Versión configuración. Cada cambio realizado debe incrementar este campo.
    int32 protocol_conf = 3;                // Protocolo seleccionado. 0 -> MQTT, 1 -> UDP, 2 -> TCP, 3 -> BLE.
    int32 acc_sampling = 4;
    int32 gyro_sensibility = 5;  
    int32 bme688_sampling = 6;
    int32 send_interval_ms = 7;             // Tiempo en milisegundos entre paquetes de datos (continuo o discontinuo).
    int32 discontinuous_sleep_time = 8;     // Tiempo en milisegundos que se irá a dormir la ESP. Cuando es > 0 se corre el modo discontinuo.
    int32 discontinuous_window_size = 9;    // Cantidad de datos que se enviarán antes de irse a deep sleep.
    int32 tcp_port = 10;
    int32 udp_port = 11;        
    string host_ip_addr = 12;               // IPv4 de la raspberry (192.168.1.1 por ejemplo)
    string ssid = 13;                       // Nombre WIFI
    string passwd = 14;                     // Contraseña WIFI
    string mqtt_broker = 15;                // URI del broker MQTT (ej: mqtt://host:1883)
}

// ACK de configuración
message ConfigAck {
    string id_device = 1;
    int32 config_version = 2;
    bool applied = 3;
}

// Log de eventos
message Log {
    int32 id_device = 1;
    int64 time_client = 2;
    int64 time_server = 3;
}

// Paquete de datos 1
message Data_1 {
    string id_device = 1;
    float temperature = 2;
    int32 press = 3;
    int32 hum = 4;
    float co = 5;
    float rms = 6;
    float amp_x = 7;
    float freq_x = 8;
    float amp_y = 9;
    float freq_y = 10;
    float amp_z = 11;
    float freq_z = 12;  
    float mag_x = 13;
    float mag_y = 14;
    float mag_z = 15;
    int32 config_version_applied = 16; // Versión de config aplicada en el dispositivo
}

// Paquete de datos 2
message Data_2 {
    string id_device = 1;
    float acc_x = 2;
    float acc_y = 3;
    float acc_z = 4;
    float gyr_x = 5;
    float gyr_y = 6;
    float gyr_z = 7;
    int64 time_client = 8;
    int32 config_version_applied = 9;
}