/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: schema.proto */

#ifndef PROTOBUF_C_schema_2eproto__INCLUDED
#define PROTOBUF_C_schema_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif


typedef struct Config Config;
typedef struct ConfigAck ConfigAck;
typedef struct Data1 Data1;
typedef struct Data2 Data2;


/* --- enums --- */


/* --- messages --- */

/*
 * Configuración del dispositivo
 */
struct  Config
{
  ProtobufCMessage base;
  /*
   * Identificador del dispositivo.
   */
  char *id_device;
  /*
   * Versión configuración. Cada cambio realizado debe incrementar este campo.
   */
  int32_t config_version;
  /*
   * Protocolo seleccionado. 0 -> MQTT, 1 -> UDP, 2 -> TCP, 3 -> BLE.
   */
  int32_t protocol_conf;
  int32_t acc_sampling;
  int32_t gyro_sensibility;
  int32_t bme688_sampling;
  /*
   * Segundos entre paquetes, para Data_1 y Data_2.
   */
  uint32_t send_interval_s;
  /*
   * 0 = sin espera: tan rápido como dejen el bus y el transporte.
   */
  /*
   * Tiempo en segundos que se irá a dormir la ESP. Cuando es > 0 se corre el modo discontinuo.
   */
  uint32_t sleep_time_s;
  /*
   * Cantidad de datos que se enviarán antes de irse a deep sleep.
   */
  int32_t sleep_window_size;
  int32_t tcp_port;
  int32_t udp_port;
  /*
   * IPv4 de la raspberry (192.168.1.1 por ejemplo)
   */
  char *host_ip_addr;
  /*
   * Nombre WIFI
   */
  char *ssid;
  /*
   * Contraseña WIFI
   */
  char *passwd;
  /*
   * URI del broker MQTT (ej: mqtt://host:1883)
   */
  char *mqtt_broker;
  /*
   * Hora
   */
  uint32_t time_client;
};
#define CONFIG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&config__descriptor) \
, (char *)protobuf_c_empty_string, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0 }


/*
 * ACK de configuración
 */
struct  ConfigAck
{
  ProtobufCMessage base;
  char *id_device;
  int32_t config_version;
  protobuf_c_boolean applied;
  uint32_t time_client;
};
#define CONFIG_ACK__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&config_ack__descriptor) \
, (char *)protobuf_c_empty_string, 0, 0, 0 }


/*
 * Paquete de datos 1: telemetría ambiental (BME688).
 * Va en su propio mensaje porque su ritmo natural es otro: la temperatura, la
 * presión y la humedad cambian en segundos o minutos, no en milisegundos.
 * Enviarla al ritmo del acelerómetro era gastar ancho de banda y batería en
 * repetir el mismo valor. Conserva el nombre Data_1 del contrato original.
 */
struct  Data1
{
  ProtobufCMessage base;
  char *id_device;
  float temperature;
  int32_t press;
  int32_t hum;
  /*
   * OJO: hoy guarda la resistencia de gas cruda del BME688, no CO.
   */
  float co;
  int32_t config_version_applied;
  uint32_t time_client;
};
#define DATA_1__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&data_1__descriptor) \
, (char *)protobuf_c_empty_string, 0, 0, 0, 0, 0, 0 }


/*
 * Paquete de datos 2: telemetría inercial (BMI270 + BMM350).
 * Los tres sensores comparten el ritmo rápido, que es el que manda en este
 * mensaje. El magnetómetro vive acá y no en Data_1 porque se configura al
 * mismo ODR que el acelerómetro. Conserva el nombre Data_2 del contrato
 * original.
 */
struct  Data2
{
  ProtobufCMessage base;
  char *id_device;
  float acc_x;
  float acc_y;
  float acc_z;
  float gyr_x;
  float gyr_y;
  float gyr_z;
  float mag_x;
  float mag_y;
  float mag_z;
  int32_t config_version_applied;
  uint32_t time_client;
};
#define DATA_2__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&data_2__descriptor) \
, (char *)protobuf_c_empty_string, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }


/* Config methods */
void   config__init
                     (Config         *message);
size_t config__get_packed_size
                     (const Config   *message);
size_t config__pack
                     (const Config   *message,
                      uint8_t             *out);
size_t config__pack_to_buffer
                     (const Config   *message,
                      ProtobufCBuffer     *buffer);
Config *
       config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   config__free_unpacked
                     (Config *message,
                      ProtobufCAllocator *allocator);
/* ConfigAck methods */
void   config_ack__init
                     (ConfigAck         *message);
size_t config_ack__get_packed_size
                     (const ConfigAck   *message);
size_t config_ack__pack
                     (const ConfigAck   *message,
                      uint8_t             *out);
size_t config_ack__pack_to_buffer
                     (const ConfigAck   *message,
                      ProtobufCBuffer     *buffer);
ConfigAck *
       config_ack__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   config_ack__free_unpacked
                     (ConfigAck *message,
                      ProtobufCAllocator *allocator);
/* Data1 methods */
void   data_1__init
                     (Data1         *message);
size_t data_1__get_packed_size
                     (const Data1   *message);
size_t data_1__pack
                     (const Data1   *message,
                      uint8_t             *out);
size_t data_1__pack_to_buffer
                     (const Data1   *message,
                      ProtobufCBuffer     *buffer);
Data1 *
       data_1__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   data_1__free_unpacked
                     (Data1 *message,
                      ProtobufCAllocator *allocator);
/* Data2 methods */
void   data_2__init
                     (Data2         *message);
size_t data_2__get_packed_size
                     (const Data2   *message);
size_t data_2__pack
                     (const Data2   *message,
                      uint8_t             *out);
size_t data_2__pack_to_buffer
                     (const Data2   *message,
                      ProtobufCBuffer     *buffer);
Data2 *
       data_2__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   data_2__free_unpacked
                     (Data2 *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Config_Closure)
                 (const Config *message,
                  void *closure_data);
typedef void (*ConfigAck_Closure)
                 (const ConfigAck *message,
                  void *closure_data);
typedef void (*Data1_Closure)
                 (const Data1 *message,
                  void *closure_data);
typedef void (*Data2_Closure)
                 (const Data2 *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor config__descriptor;
extern const ProtobufCMessageDescriptor config_ack__descriptor;
extern const ProtobufCMessageDescriptor data_1__descriptor;
extern const ProtobufCMessageDescriptor data_2__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_schema_2eproto__INCLUDED */
