# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: schema.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'schema.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cschema.proto\"\xe5\x02\n\x06\x43onfig\x12\x11\n\tid_device\x18\x01 \x01(\t\x12\x16\n\x0e\x63onfig_version\x18\x02 \x01(\x05\x12\x15\n\rprotocol_conf\x18\x03 \x01(\x05\x12\x14\n\x0c\x61\x63\x63_sampling\x18\x04 \x01(\x05\x12\x18\n\x10gyro_sensibility\x18\x05 \x01(\x05\x12\x17\n\x0f\x62me688_sampling\x18\x06 \x01(\x05\x12\x17\n\x0fsend_interval_s\x18\x07 \x01(\r\x12\x14\n\x0csleep_time_s\x18\x08 \x01(\r\x12\x19\n\x11sleep_window_size\x18\t \x01(\x05\x12\x10\n\x08tcp_port\x18\n \x01(\x05\x12\x10\n\x08udp_port\x18\x0b \x01(\x05\x12\x14\n\x0chost_ip_addr\x18\x0c \x01(\t\x12\x0c\n\x04ssid\x18\r \x01(\t\x12\x0e\n\x06passwd\x18\x0e \x01(\t\x12\x13\n\x0bmqtt_broker\x18\x0f \x01(\t\x12\x13\n\x0btime_client\x18\x10 \x01(\rJ\x04\x08\x11\x10\x12\"\\\n\tConfigAck\x12\x11\n\tid_device\x18\x01 \x01(\t\x12\x16\n\x0e\x63onfig_version\x18\x02 \x01(\x05\x12\x0f\n\x07\x61pplied\x18\x03 \x01(\x08\x12\x13\n\x0btime_client\x18\x04 \x01(\r\"\x8d\x01\n\x06\x44\x61ta_1\x12\x11\n\tid_device\x18\x01 \x01(\t\x12\x13\n\x0btemperature\x18\x02 \x01(\x02\x12\r\n\x05press\x18\x03 \x01(\x05\x12\x0b\n\x03hum\x18\x04 \x01(\x05\x12\n\n\x02\x63o\x18\x05 \x01(\x02\x12\x1e\n\x16\x63onfig_version_applied\x18\x06 \x01(\x05\x12\x13\n\x0btime_client\x18\x07 \x01(\r\"\xd7\x01\n\x06\x44\x61ta_2\x12\x11\n\tid_device\x18\x01 \x01(\t\x12\r\n\x05\x61\x63\x63_x\x18\x02 \x01(\x02\x12\r\n\x05\x61\x63\x63_y\x18\x03 \x01(\x02\x12\r\n\x05\x61\x63\x63_z\x18\x04 \x01(\x02\x12\r\n\x05gyr_x\x18\x05 \x01(\x02\x12\r\n\x05gyr_y\x18\x06 \x01(\x02\x12\r\n\x05gyr_z\x18\x07 \x01(\x02\x12\r\n\x05mag_x\x18\x08 \x01(\x02\x12\r\n\x05mag_y\x18\t \x01(\x02\x12\r\n\x05mag_z\x18\n \x01(\x02\x12\x1e\n\x16\x63onfig_version_applied\x18\x0b \x01(\x05\x12\x13\n\x0btime_client\x18\x0c \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'schema_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONFIG']._serialized_start=17
  _globals['_CONFIG']._serialized_end=374
  _globals['_CONFIGACK']._serialized_start=376
  _globals['_CONFIGACK']._serialized_end=468
  _globals['_DATA_1']._serialized_start=471
  _globals['_DATA_1']._serialized_end=612
  _globals['_DATA_2']._serialized_start=615
  _globals['_DATA_2']._serialized_end=830
# @@protoc_insertion_point(module_scope)
