# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: schema.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'schema.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cschema.proto\"\x84\x02\n\x06\x43onfig\x12\x11\n\tid_device\x18\x01 \x01(\x05\x12\x13\n\x0bstatus_conf\x18\x02 \x01(\x05\x12\x15\n\rprotocol_conf\x18\x03 \x01(\x05\x12\x14\n\x0c\x61\x63\x63_sampling\x18\x04 \x01(\x05\x12\x18\n\x10gyro_sensibility\x18\x05 \x01(\x05\x12\x17\n\x0f\x62me688_sampling\x18\x06 \x01(\x05\x12\x1a\n\x12\x64iscontinuous_time\x18\x07 \x01(\x05\x12\x10\n\x08tcp_port\x18\x08 \x01(\x05\x12\x10\n\x08udp_port\x18\t \x01(\x05\x12\x14\n\x0chost_ip_addr\x18\n \x01(\t\x12\x0c\n\x04ssid\x18\x0b \x01(\t\x12\x0e\n\x06passwd\x18\x0c \x01(\t\"B\n\x03Log\x12\x11\n\tid_device\x18\x01 \x01(\x05\x12\x13\n\x0btime_client\x18\x02 \x01(\x03\x12\x13\n\x0btime_server\x18\x03 \x01(\x03\"\xc2\x01\n\x06\x44\x61ta_1\x12\x11\n\tid_device\x18\x01 \x01(\x05\x12\x13\n\x0btemperature\x18\x02 \x01(\x05\x12\r\n\x05press\x18\x03 \x01(\x05\x12\x0b\n\x03hum\x18\x04 \x01(\x05\x12\n\n\x02\x63o\x18\x05 \x01(\x02\x12\x0b\n\x03rms\x18\x06 \x01(\x02\x12\r\n\x05\x61mp_x\x18\x07 \x01(\x02\x12\x0e\n\x06\x66req_x\x18\x08 \x01(\x02\x12\r\n\x05\x61mp_y\x18\t \x01(\x02\x12\x0e\n\x06\x66req_y\x18\n \x01(\x02\x12\r\n\x05\x61mp_z\x18\x0b \x01(\x02\x12\x0e\n\x06\x66req_z\x18\x0c \x01(\x02\"\x90\x01\n\x06\x44\x61ta_2\x12\x11\n\tid_device\x18\x01 \x01(\x05\x12\x0e\n\x06racc_x\x18\x02 \x01(\x02\x12\x0e\n\x06racc_y\x18\x03 \x01(\x02\x12\x0e\n\x06racc_z\x18\x04 \x01(\x02\x12\x0e\n\x06rgyr_x\x18\x05 \x01(\x02\x12\x0e\n\x06rgyr_y\x18\x06 \x01(\x02\x12\x0e\n\x06rgyr_z\x18\x07 \x01(\x02\x12\x13\n\x0btime_client\x18\x08 \x01(\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'schema_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONFIG']._serialized_start=17
  _globals['_CONFIG']._serialized_end=277
  _globals['_LOG']._serialized_start=279
  _globals['_LOG']._serialized_end=345
  _globals['_DATA_1']._serialized_start=348
  _globals['_DATA_1']._serialized_end=542
  _globals['_DATA_2']._serialized_start=545
  _globals['_DATA_2']._serialized_end=689
# @@protoc_insertion_point(module_scope)
